AllCops:
  RunRailsCops: true
  DisplayCopNames: true
  Exclude:
    - 'Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'app/views/**/*.jbuilder'
    - 'spec/support/product.rb'

Style/Documentation:
  Enabled: False

Style/ClassAndModuleChildren:
  Enabled: False

Metrics/LineLength:
  Exclude:
    - 'spec/**/*'
